# Settings for the generation of summa forcing data from gmet forcing
---
base_settings:
  case_name: tuolumne
  working_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne
input_files:
  catchment_shp: /Users/drc858/Data/TuolumneWork/shp/huc12x.tuolumne.gpkg
  attribute_nc: /Users/drc858/Data/gmet_to_summa/Tuolumne/summa/settings/attributes.wUShuc12.v2.nc
gmet:
  gmet_forcing_dir: /Users/drc858/Data/gmet_to_summa/gmet
  gmet_tmp_forcing_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/tmp
  prep_suffix: '_prep.nc'
  gmet_input_var:
    - pcp
    - t_max
    - t_min
easymore:
  # The forcing shp will be located in the easymore_intersect_dir
  forcing_shp: forcing_shp.shp
  easymore_temp_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/easymore/temp
  easymore_intersect_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/easymore/intersect
  easymore_output_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/easymore/output
  catchment_shp_hru_id_field: 'HUCIDXint'
  catchment_shp_lat_id_field: 'CENTROID_Y'
  catchment_shp_lon_id_field: 'CENTROID_X'
metsim:
  metsim_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/metsim
  metsim_input_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/metsim/input
  metsim_output_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/metsim/output
  metsim_base_config: /Users/drc858/GitHub/gmet_to_summa/settings/metsim_base_config.yaml
  metsim_timestep_minutes: 60
  metsim_domain_nc: domain.nc
  out_freq: Y
summa:
  summa_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/summa
  summa_forcing_dir: /Users/drc858/Data/gmet_to_summa/Tuolumne/summa/forcing
